//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DesarrolloWeb2Front.HobbiesWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HobbieWSSoap", Namespace="http://tempuri.org/")]
    public partial class HobbieWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HobbiesGetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback HobbiesGetByIdlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HobbieWS() {
            this.Url = global::DesarrolloWeb2Front.Properties.Settings.Default.DesarrolloWeb2Front_HobbiesWS_HobbieWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HobbiesGetAllCompletedEventHandler HobbiesGetAllCompleted;
        
        /// <remarks/>
        public event HobbiesGetByIdlCompletedEventHandler HobbiesGetByIdlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HobbiesGetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HobbiesDto[] HobbiesGetAll() {
            object[] results = this.Invoke("HobbiesGetAll", new object[0]);
            return ((HobbiesDto[])(results[0]));
        }
        
        /// <remarks/>
        public void HobbiesGetAllAsync() {
            this.HobbiesGetAllAsync(null);
        }
        
        /// <remarks/>
        public void HobbiesGetAllAsync(object userState) {
            if ((this.HobbiesGetAllOperationCompleted == null)) {
                this.HobbiesGetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHobbiesGetAllOperationCompleted);
            }
            this.InvokeAsync("HobbiesGetAll", new object[0], this.HobbiesGetAllOperationCompleted, userState);
        }
        
        private void OnHobbiesGetAllOperationCompleted(object arg) {
            if ((this.HobbiesGetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HobbiesGetAllCompleted(this, new HobbiesGetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HobbiesGetByIdl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HobbiesDto HobbiesGetByIdl(string code) {
            object[] results = this.Invoke("HobbiesGetByIdl", new object[] {
                        code});
            return ((HobbiesDto)(results[0]));
        }
        
        /// <remarks/>
        public void HobbiesGetByIdlAsync(string code) {
            this.HobbiesGetByIdlAsync(code, null);
        }
        
        /// <remarks/>
        public void HobbiesGetByIdlAsync(string code, object userState) {
            if ((this.HobbiesGetByIdlOperationCompleted == null)) {
                this.HobbiesGetByIdlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHobbiesGetByIdlOperationCompleted);
            }
            this.InvokeAsync("HobbiesGetByIdl", new object[] {
                        code}, this.HobbiesGetByIdlOperationCompleted, userState);
        }
        
        private void OnHobbiesGetByIdlOperationCompleted(object arg) {
            if ((this.HobbiesGetByIdlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HobbiesGetByIdlCompleted(this, new HobbiesGetByIdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HobbiesDto {
        
        private string codigoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HobbiesGetAllCompletedEventHandler(object sender, HobbiesGetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HobbiesGetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HobbiesGetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HobbiesDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HobbiesDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HobbiesGetByIdlCompletedEventHandler(object sender, HobbiesGetByIdlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HobbiesGetByIdlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HobbiesGetByIdlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HobbiesDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HobbiesDto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591