//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DesarrolloWeb2Front.EstusianteWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EstudianteWSSoap", Namespace="http://tempuri.org/")]
    public partial class EstudianteWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllStudenOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentCreateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EstudianteWS() {
            this.Url = global::DesarrolloWeb2Front.Properties.Settings.Default.DesarrolloWeb2Front_EstusianteWS_EstudianteWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllStudenCompletedEventHandler GetAllStudenCompleted;
        
        /// <remarks/>
        public event StudentByIdCompletedEventHandler StudentByIdCompleted;
        
        /// <remarks/>
        public event StudentUpdateCompletedEventHandler StudentUpdateCompleted;
        
        /// <remarks/>
        public event StudentDeleteCompletedEventHandler StudentDeleteCompleted;
        
        /// <remarks/>
        public event StudentCreateCompletedEventHandler StudentCreateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStuden", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstudianteDto[] GetAllStuden() {
            object[] results = this.Invoke("GetAllStuden", new object[0]);
            return ((EstudianteDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllStudenAsync() {
            this.GetAllStudenAsync(null);
        }
        
        /// <remarks/>
        public void GetAllStudenAsync(object userState) {
            if ((this.GetAllStudenOperationCompleted == null)) {
                this.GetAllStudenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStudenOperationCompleted);
            }
            this.InvokeAsync("GetAllStuden", new object[0], this.GetAllStudenOperationCompleted, userState);
        }
        
        private void OnGetAllStudenOperationCompleted(object arg) {
            if ((this.GetAllStudenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllStudenCompleted(this, new GetAllStudenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstudianteDto StudentById(string code) {
            object[] results = this.Invoke("StudentById", new object[] {
                        code});
            return ((EstudianteDto)(results[0]));
        }
        
        /// <remarks/>
        public void StudentByIdAsync(string code) {
            this.StudentByIdAsync(code, null);
        }
        
        /// <remarks/>
        public void StudentByIdAsync(string code, object userState) {
            if ((this.StudentByIdOperationCompleted == null)) {
                this.StudentByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentByIdOperationCompleted);
            }
            this.InvokeAsync("StudentById", new object[] {
                        code}, this.StudentByIdOperationCompleted, userState);
        }
        
        private void OnStudentByIdOperationCompleted(object arg) {
            if ((this.StudentByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentByIdCompleted(this, new StudentByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentUpdate(string identificacion, string nombre, string Apellido, string direccion, string telefono) {
            object[] results = this.Invoke("StudentUpdate", new object[] {
                        identificacion,
                        nombre,
                        Apellido,
                        direccion,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentUpdateAsync(string identificacion, string nombre, string Apellido, string direccion, string telefono) {
            this.StudentUpdateAsync(identificacion, nombre, Apellido, direccion, telefono, null);
        }
        
        /// <remarks/>
        public void StudentUpdateAsync(string identificacion, string nombre, string Apellido, string direccion, string telefono, object userState) {
            if ((this.StudentUpdateOperationCompleted == null)) {
                this.StudentUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentUpdateOperationCompleted);
            }
            this.InvokeAsync("StudentUpdate", new object[] {
                        identificacion,
                        nombre,
                        Apellido,
                        direccion,
                        telefono}, this.StudentUpdateOperationCompleted, userState);
        }
        
        private void OnStudentUpdateOperationCompleted(object arg) {
            if ((this.StudentUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentUpdateCompleted(this, new StudentUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentDelete(string identificacion) {
            object[] results = this.Invoke("StudentDelete", new object[] {
                        identificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentDeleteAsync(string identificacion) {
            this.StudentDeleteAsync(identificacion, null);
        }
        
        /// <remarks/>
        public void StudentDeleteAsync(string identificacion, object userState) {
            if ((this.StudentDeleteOperationCompleted == null)) {
                this.StudentDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentDeleteOperationCompleted);
            }
            this.InvokeAsync("StudentDelete", new object[] {
                        identificacion}, this.StudentDeleteOperationCompleted, userState);
        }
        
        private void OnStudentDeleteOperationCompleted(object arg) {
            if ((this.StudentDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentDeleteCompleted(this, new StudentDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentCreate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentCreate(string identificacion, string nombre, string Apellido, string direccion, string telefono) {
            object[] results = this.Invoke("StudentCreate", new object[] {
                        identificacion,
                        nombre,
                        Apellido,
                        direccion,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentCreateAsync(string identificacion, string nombre, string Apellido, string direccion, string telefono) {
            this.StudentCreateAsync(identificacion, nombre, Apellido, direccion, telefono, null);
        }
        
        /// <remarks/>
        public void StudentCreateAsync(string identificacion, string nombre, string Apellido, string direccion, string telefono, object userState) {
            if ((this.StudentCreateOperationCompleted == null)) {
                this.StudentCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentCreateOperationCompleted);
            }
            this.InvokeAsync("StudentCreate", new object[] {
                        identificacion,
                        nombre,
                        Apellido,
                        direccion,
                        telefono}, this.StudentCreateOperationCompleted, userState);
        }
        
        private void OnStudentCreateOperationCompleted(object arg) {
            if ((this.StudentCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentCreateCompleted(this, new StudentCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstudianteDto {
        
        private string identificacionField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string direccionField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllStudenCompletedEventHandler(object sender, GetAllStudenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllStudenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllStudenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstudianteDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstudianteDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StudentByIdCompletedEventHandler(object sender, StudentByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstudianteDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstudianteDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StudentUpdateCompletedEventHandler(object sender, StudentUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StudentDeleteCompletedEventHandler(object sender, StudentDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StudentCreateCompletedEventHandler(object sender, StudentCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591